hand_eye_mode: eye_to_hand
board_cols: 8
board_rows: 8
square_size: 25.0
points:
- x: '111'
  y: '123'
  u: '485.3'
  v: '156.0'
- x: '12'
  y: '23'
  u: '562.1'
  v: '141.4'
- x: '31'
  y: '44'
  u: '442.2'
  v: '267.9'
- x: '122'
  y: '33'
  u: '266.7'
  v: '247.1'
- x: '1212'
  y: '25'
  u: '-346.9'
  v: '156.3'
- x: '124'
  y: '656'
  u: '1220.4'
  v: '-986.0'
- x: '44'
  y: '55'
  u: '463.7'
  v: '192.2'
- x: '6'
  y: '1'
  u: '476.8'
  v: '280.9'
- x: '467'
  y: '7'
  u: '496.0'
  v: '330.9'
point_result: '手眼模式：眼在手外

  拟合 RMS：181.9465


  仿射系数（u, v -> X）：

  a=-1.162432, b=-0.696790, c=822.662445


  仿射系数（u, v -> Y）：

  d=0.054822, e=-0.468520, f=123.628982'
intrinsic_result: 未检测到棋盘格角点，请检查棋盘格行列数或图像。
